import React, { useState } from "react";
import { ClipboardList, RefreshCw, WifiOff } from "lucide-react";
import { nextId, nowStamp } from "../../data/appState";
export function OfflineFastEntryModule({ appState, setAppState }) {
  const [fails, setFails] = useState(0); const [offline, setOffline] = useState(false); const [name, setName] = useState(""); const [message, setMessage] = useState("Heartbeat checks run every 30 seconds.");
  const fail = () => { const next = fails + 1; setFails(next); if (next >= 3) { setOffline(true); setMessage("Offline Mode - simplified check-in is active. Your entry will be uploaded when connection is restored."); } else setMessage(`Heartbeat failed ${next}/3.`); };
  const queue = (type) => { const item = { id: nextId("OFF"), entryType: type, name: name || (type === "OfflineQR" ? "Saved QR visitor" : "Offline visitor"), status: "Pending", createdAt: nowStamp(), count: 1 }; setAppState(s => ({ ...s, offlineQueue: [item, ...s.offlineQueue], logs: [`${nowStamp()} - ${type} stored in encrypted local queue`, ...s.logs].slice(0,20) })); setMessage(`${type} recorded offline with sync_status = Pending.`); };
  const sync = () => { setAppState(s => ({ ...s, offlineQueue: s.offlineQueue.map(q => q.status === "Pending" ? { ...q, status: "Synced" } : q), visits: [...s.offlineQueue.filter(q=>q.status==="Pending").map(q=>({id:nextId("VISIT"), passId:q.id, visitorId:q.id, name:q.name, type:"Offline", channel:q.entryType, status:"inside", count:q.count, checkInTime:q.createdAt, checkOutTime:"", checkOutMethod:"", zone:"Main Gate"})), ...s.visits], logs: [`${nowStamp()} - offline queue synchronized`, ...s.logs].slice(0,20) })); setOffline(false); setFails(0); setMessage("Connection restored. Pending records uploaded and staff dashboard updated."); };
  return <section className="panel"><div className="sectionHead"><div><p className="eyebrow">Subsystem 1</p><h2>Offline & Fast Entry Module</h2><p>Heartbeat monitoring, offline QR scan, simplified offline form, local encrypted queue and sync recovery.</p></div><WifiOff size={30}/></div><div className={`offlineBanner ${offline ? "active" : ""}`}><WifiOff/><strong>{offline ? "Offline Mode Active" : "Online Mode"}</strong><span>{message}</span></div><div className="buttonRow"><button className="secondaryButton" onClick={fail}>Record Failed Heartbeat</button><button className="secondaryButton" onClick={()=>{setOffline(true);setFails(3)}}>Activate Offline Mode</button><button className="primaryButton" onClick={sync}><RefreshCw size={18}/> Restore Connection & Sync</button></div><div className="split"><div className="subPanel"><h3>Offline QR</h3><p>Store QR payload locally until backend verification returns.</p><button className="primaryButton" onClick={()=>queue("OfflineQR")}>Scan Saved QR Offline</button></div><div className="subPanel"><h3>Simplified Form</h3><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Offline visitor name"/></label><button className="primaryButton" onClick={()=>queue("OfflineForm")}><ClipboardList size={18}/> Check In Offline</button></div></div><table className="dataTable"><thead><tr><th>Offline ID</th><th>Type</th><th>Name</th><th>Status</th><th>Captured</th></tr></thead><tbody>{appState.offlineQueue.map(q=><tr key={q.id}><td>{q.id}</td><td>{q.entryType}</td><td>{q.name}</td><td>{q.status}</td><td>{q.createdAt}</td></tr>)}</tbody></table></section>;
}
