import React from "react";
import { Bell, CheckCircle2, Clock, LogOut } from "lucide-react";
import { liveHeadCount, nowStamp } from "../../data/appState";

export function VisitorCheckOutModule({ appState, setAppState, mobile = false }) {
  const inside = appState.visits.filter(v => v.status === "inside");
  const checkout = (id, method = "self_reported") => setAppState(s => ({ ...s, visits: s.visits.map(v => v.id === id ? { ...v, status: "checked_out", checkOutTime: nowStamp(), checkOutMethod: method } : v), logs: [`${nowStamp()} - checkout updated by ${method}`, ...s.logs].slice(0,20) }));
  const stillInside = (id) => setAppState(s => ({ ...s, visits: s.visits.map(v => v.id === id ? { ...v, stillInside: true, notificationTime: "Still inside" } : v), alerts: [{ id: `AL-${Date.now()}`, message: "Visitor confirmed Still Inside. Follow up required.", time: nowStamp(), severity: "Warning", status: "Active" }, ...s.alerts], logs: [`${nowStamp()} - still-inside alert created`, ...s.logs].slice(0,20) }));
  const notify = () => setAppState(s => ({ ...s, visits: s.visits.map(v => v.status === "inside" ? { ...v, notificationTime: "6:45 PM" } : v), logs: [`${nowStamp()} - 6:45 PM checkout reminders sent`, ...s.logs].slice(0,20) }));
  const autoCheckout = () => setAppState(s => ({ ...s, visits: s.visits.map(v => v.status === "inside" ? { ...v, status: "checked_out", checkOutTime: "7:00 PM", checkOutMethod: "auto" } : v), logs: [`${nowStamp()} - 7:00 PM auto-checkout completed and daily summary generated`, ...s.logs].slice(0,20) }));
  if (mobile) return <section className="mobileModule"><div className="checkoutCard"><Clock size={40}/><strong>Closing reminder</strong><span>Taman Botani Johor closes at 7:00 PM. Have you left the park?</span></div><button className="primaryButton" onClick={() => inside[0] && checkout(inside[0].id)}><CheckCircle2 size={18}/> I Have Left</button><button className="secondaryButton" onClick={() => inside[0] && stillInside(inside[0].id)}>Still Inside</button></section>;
  return <section className="panel"><div className="sectionHead"><div><p className="eyebrow">Subsystem 1</p><h2>Checkout Control</h2><p>Entrance staff controls closing notifications, self check-out, still-inside alerts and 7:00 PM auto checkout.</p></div><LogOut size={30}/></div><div className="metricRow compact"><div className="statusItem"><span>Live visitor count</span><strong>{liveHeadCount(appState.visits)}</strong></div><div className="statusItem"><span>Today's visitor count</span><strong>{appState.visits.reduce((s,v)=>s+Number(v.count||1),0)}</strong></div><div className="statusItem"><span>Self-reported check-outs</span><strong>{appState.visits.filter(v=>v.checkOutMethod==="self_reported").length}</strong></div><div className="statusItem"><span>Auto check-outs</span><strong>{appState.visits.filter(v=>v.checkOutMethod==="auto").length}</strong></div></div><div className="buttonRow"><button className="secondaryButton" onClick={notify}><Bell size={18}/> Send 6:45 PM Notification</button><button className="primaryButton" onClick={autoCheckout}><LogOut size={18}/> Auto Checkout All</button></div><table className="dataTable"><thead><tr><th>Name</th><th>Visitor / Group ID</th><th>Status</th><th>Channel</th><th>Count</th><th>Check In</th><th>Notification</th><th>Action</th></tr></thead><tbody>{inside.map(v=><tr key={v.id}><td>{v.name}</td><td>{v.visitorId}</td><td>status = 'inside'</td><td>{v.channel}</td><td>{v.count}</td><td>{v.checkInTime}</td><td>{v.notificationTime || "Not sent"}</td><td><button className="miniButton" onClick={()=>checkout(v.id)}>I Have Left</button><button className="miniButton" onClick={()=>stillInside(v.id)}>Still Inside</button></td></tr>)}</tbody></table></section>;
}
