import React, { useState } from "react";
import { Download } from "lucide-react";
import { useToast } from "../../../components/ToastContext";
import { downloadTextFile } from "../utils/download";

export function HistoryTable() {
  const [historyOpen, setHistoryOpen] = useState("Daily Visitor Summary");
  const { notify } = useToast();

  const rows = [
    ["Daily Visitor Summary", "02/06/2026 18:00", "PDF", "Scheduled", "Ready"],
    ["Historical Visitor Pattern", "01/06/2026 09:12", "Excel", "Manual", "Ready"],
    ["Operational Analytics", "31/05/2026 18:00", "PDF", "Scheduled", "Ready"]
  ];

  function handleDownload(row, e) {
    e.stopPropagation();
    const fileName = `${row[0].replaceAll(" ", "_")}_2026.${row[2] === "Excel" ? "csv" : "txt"}`;
    const content = [
      `${row[0]}`,
      `Generated: ${row[1]}`,
      `Format: ${row[2]}`,
      `Trigger: ${row[3]}`,
      `Status: ${row[4]}`,
      `Generated by: ${row[3] === "Scheduled" ? "System scheduler" : "Staff admin"}`
    ].join("\n");
    downloadTextFile(fileName, content);
    notify(`${row[0]} downloaded as ${fileName}.`, { title: "Download started", tone: "good" });
  }

  return (
    <section className="panel spanThree">
      <div className="panelHeader"><div><h2>Generated Report History</h2><p>Past generated files can be downloaded again or removed.</p></div></div>
      <table className="dataTable">
        <thead>
          <tr><th>Report</th><th>Generated</th><th>Format</th><th>Trigger</th><th>Status</th><th>Action</th></tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <React.Fragment key={row.join("-")}>
              <tr
                className={historyOpen === row[0] ? "selectedRow" : ""}
                onClick={() => setHistoryOpen(historyOpen === row[0] ? "" : row[0])}
              >
                {row.map((cell, index) => (
                  <td key={cell} className={index === 4 ? "statusCell" : ""}>{cell}</td>
                ))}
                <td><button className="ghostButton" onClick={(e) => handleDownload(row, e)}><Download size={14} /> Download</button></td>
              </tr>
              {historyOpen === row[0] && (
                <tr className="expandedRecordRow">
                  <td colSpan="6">
                    <div className="reportHistoryDetails">
                      <div><span>File name</span><strong>{row[0].replaceAll(" ", "_")}_2026.pdf</strong></div>
                      <div><span>Generated by</span><strong>{row[3] === "Scheduled" ? "System scheduler" : "Staff admin"}</strong></div>
                      <div><span>Available actions</span><strong>Preview, download again, delete archived copy</strong></div>
                    </div>
                  </td>
                </tr>
              )}
            </React.Fragment>
          ))}
        </tbody>
      </table>
    </section>
  );
}